<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Seed users
        DB::table('users')->insert([
            [
                'id' => 1,
                'username' => 'superadmin',
                'name' => 'IT Super Admin',
                'email' => 'admin@ptabb.com',
                'password' => bcrypt('abb_super2026'),
                'role' => 'super_admin',
                'last_login' => '2026-07-20 11:03:56',
                'created_at' => '2026-03-07 13:38:10',
                'updated_at' => '2026-03-07 13:38:10',
            ],
            [
                'id' => 2,
                'username' => 'hrd_admin',
                'name' => 'HR Department',
                'email' => 'hrd@ptabb.com',
                'password' => bcrypt('abb_hrd2026'),
                'role' => 'hr_admin',
                'last_login' => '2026-03-10 09:13:07',
                'created_at' => '2026-03-07 13:38:10',
                'updated_at' => '2026-03-07 13:38:10',
            ],
            [
                'id' => 3,
                'username' => 'crew_admin',
                'name' => 'Crewing Department',
                'email' => 'crewing@ptabb.com',
                'password' => bcrypt('abb_crew2026'),
                'role' => 'crew_admin',
                'last_login' => '2026-03-10 09:12:48',
                'created_at' => '2026-03-07 13:38:10',
                'updated_at' => '2026-03-07 13:38:10',
            ],
            [
                'id' => 4,
                'username' => 'pr_admin',
                'name' => 'PR Department',
                'email' => 'pr@ptabb.com',
                'password' => bcrypt('abb_pr2026'),
                'role' => 'pr_admin',
                'last_login' => '2026-03-11 12:06:36',
                'created_at' => '2026-03-09 02:01:26',
                'updated_at' => '2026-03-09 02:01:26',
            ],
        ]);

        // 2. Seed fleet_categories
        DB::table('fleet_categories')->insert([
            ['id' => 1, 'name' => 'Bulk Cement Carrier', 'description' => 'Kapal khusus pengangkut semen curah', 'created_at' => '2025-12-17 04:53:11', 'updated_at' => '2025-12-17 04:53:11'],
            ['id' => 2, 'name' => 'Pusher', 'description' => 'Kapal penarik/pendorong', 'created_at' => '2025-12-17 04:53:11', 'updated_at' => '2025-12-17 04:53:11'],
            ['id' => 3, 'name' => 'Barge', 'description' => 'Tongkang', 'created_at' => '2025-12-17 04:53:11', 'updated_at' => '2025-12-17 04:53:11'],
            ['id' => 4, 'name' => 'Pusher & Barge', 'description' => 'Kombinasi pusher dan tongkang', 'created_at' => '2025-12-17 04:53:11', 'updated_at' => '2025-12-17 04:53:11'],
        ]);

        // 3. Seed fleets
        DB::table('fleets')->insert([
            [
                'id' => 7,
                'category_id' => 1,
                'ship_name' => 'MV. IRIANA',
                'imo_number' => '9821158',
                'description' => '',
                'build_year' => 2015,
                'dwt' => 11.04,
                'capacity' => 8.86,
                'status' => 'in_service',
                'operational_area' => 'Europe',
                'voyage_route_image' => null,
                'ship_particular_pdf' => 'ship_3463756_MV__Iriana_1766677019.pdf',
                'voyage_description' => null,
                'featured_image' => 'ship_9821158_1767455250.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 10.68,
                'classification_society' => 'RINA',
                'gross_tonnage' => 7.75,
                'net_tonnage' => 3.45,
                'vessel_type' => 'PNEUMATIC & MANIFOLD',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2025-12-16 21:06:41',
                'updated_at' => '2026-01-05 02:07:49',
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'ship_name' => 'MV. PRILLY',
                'imo_number' => '9875734',
                'description' => '',
                'build_year' => null,
                'dwt' => null,
                'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Middle East',
                'voyage_route_image' => null,
                'ship_particular_pdf' => 'ship_9875734_MV__Prilly_1766677114.pdf',
                'voyage_description' => null,
                'featured_image' => 'ship_9875734_1767432025.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Bulk Carrier',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2025-12-25 08:38:34',
                'updated_at' => '2026-01-03 08:54:51',
            ],
            [
                'id' => 10,
                'category_id' => 4,
                'ship_name' => 'PB. ASUWA / ASUWA 1',
                'imo_number' => '1234567',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_1234567_1767432013.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Tug & Barge',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:14:28',
                'updated_at' => '2026-01-03 02:20:13',
            ],
            [
                'id' => 11,
                'category_id' => 4,
                'ship_name' => 'PB. KUNIMI / KUNIMI 1',
                'imo_number' => '2345678',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Southeast Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_2345678_1767431997.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Tug & Barge',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:15:05',
                'updated_at' => '2026-01-03 02:19:57',
            ],
            [
                'id' => 12,
                'category_id' => 1,
                'ship_name' => 'MV. FUYO 18',
                'imo_number' => '3456789',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Middle East',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_3456789_1767431981.png',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Bulk Carrier',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:15:57',
                'updated_at' => '2026-01-03 08:53:23',
            ],
            [
                'id' => 13,
                'category_id' => 1,
                'ship_name' => 'MV. NAGAKO',
                'imo_number' => '4567890',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_4567890_1767431967.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Bulk Carrier',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:17:01',
                'updated_at' => '2026-01-03 02:19:27',
            ],
            [
                'id' => 14,
                'category_id' => 1,
                'ship_name' => 'MV. SENSHO',
                'imo_number' => '5678901',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Europe',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_5678901_1768125420.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Bulk Carrier',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:17:31',
                'updated_at' => '2026-01-11 02:57:00',
            ],
            [
                'id' => 15,
                'category_id' => 1,
                'ship_name' => 'MV. MONTOK',
                'imo_number' => '6789012',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_docking',
                'operational_area' => 'Europe',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_6789012_1767431851.jpg',
                'flag' => 'INDONESIA',
                'deadweight' => 0.00,
                'classification_society' => 'BKI',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => 'Bulk Carrier',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-01 00:18:13',
                'updated_at' => '2026-01-03 02:17:31',
            ],
            [
                'id' => 17,
                'category_id' => null,
                'ship_name' => 'MV. KENYO',
                'imo_number' => '9876765',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_docking',
                'operational_area' => 'Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_9876765_1767426461.png',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-03 00:47:41',
                'updated_at' => '2026-01-03 02:21:39',
            ],
            [
                'id' => 18,
                'category_id' => null,
                'ship_name' => 'PB. OSHIMA 1',
                'imo_number' => '6785390',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Southeast Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_6785390_1767603442.png',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-05 01:57:22',
                'updated_at' => '2026-01-05 01:57:22',
            ],
            [
                'id' => 19,
                'category_id' => null,
                'ship_name' => 'MV. RYUOH',
                'imo_number' => '5647921',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Middle East',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_5647921_1767784825.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-07 04:20:25',
                'updated_at' => '2026-01-07 04:20:25',
            ],
            [
                'id' => 20,
                'category_id' => null,
                'ship_name' => 'MV. YURICO',
                'imo_number' => '2354876',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Middle East',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_2354876_1768125569.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-11 02:59:29',
                'updated_at' => '2026-01-11 02:59:29',
            ],
            [
                'id' => 21,
                'category_id' => null,
                'ship_name' => 'MV. RYOKO 8',
                'imo_number' => '9789878',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Europe',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_9789878_1768125615.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-11 03:00:15',
                'updated_at' => '2026-01-11 03:00:15',
            ],
            [
                'id' => 22,
                'category_id' => null,
                'ship_name' => 'MV. SOPHIA',
                'imo_number' => '1122334',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'East Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_1122334_1768125651.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-11 03:00:51',
                'updated_at' => '2026-01-11 03:00:51',
            ],
            [
                'id' => 23,
                'category_id' => null,
                'ship_name' => 'MV. UNGGUL',
                'imo_number' => '0099009',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Asia,Southeast Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_0099009_1768126755.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-11 03:01:25',
                'updated_at' => '2026-01-11 03:19:15',
            ],
            [
                'id' => 24,
                'category_id' => null,
                'ship_name' => 'MV. MUMBAI',
                'imo_number' => '6655778',
                'description' => '',
                'build_year' => null, 'dwt' => null, 'capacity' => null,
                'status' => 'in_service',
                'operational_area' => 'Asia',
                'voyage_route_image' => null, 'ship_particular_pdf' => null, 'voyage_description' => null,
                'featured_image' => 'ship_6655778_1768125725.jpg',
                'flag' => '',
                'deadweight' => 0.00,
                'classification_society' => '',
                'gross_tonnage' => 0.00,
                'net_tonnage' => 0.00,
                'vessel_type' => '',
                'loa' => null, 'lbp' => null, 'breadth' => null, 'depth' => null, 'speed' => null,
                'created_at' => '2026-01-11 03:02:05',
                'updated_at' => '2026-02-19 07:52:20',
            ]
        ]);

        // 4. Seed voyage_waypoints (Dynamically populated from live Sailink GPS API)
        // DB::table('voyage_waypoints')->truncate();

        // 5. Seed news_categories
        DB::table('news_categories')->insert([
            ['id' => 3, 'name' => 'Company News', 'slug' => 'company-news', 'description' => 'Updates and announcements from PT. ABB'],
            ['id' => 4, 'name' => 'Office Events', 'slug' => 'office-events', 'description' => 'Events and activities at PT. ABB offices'],
            ['id' => 5, 'name' => 'CSR & Sustainability', 'slug' => 'csr-sustainability', 'description' => 'Corporate Social Responsibility and sustainability initiatives'],
        ]);

        // 6. Seed news
        DB::table('news')->insert([
            [
                'id' => 2,
                'category_id' => 3,
                'title' => 'Annual Medical Check Up 2026 at TZU CHI Hospital',
                'slug' => 'annual-medical-check-up-2026-at-tzu-chi-hospital',
                'excerpt' => 'Comprehensive health screenings to ensure employee well-being and enforce maritime safety standards.',
                'content' => '<p style="text-align: justify;">As part of its commitment to employee health and workplace safety, PT. Pelayaran Andalas Bahtera Baruna conducted the 2026 Medical Check Up (MCU) for all staff members.</p><p style="text-align: justify;">The program took place at TZU CHI Hospital - PIK, North Jakarta, a modern healthcare facility equipped with comprehensive medical services and professional staff. Through thorough examinations, the company ensured that every employee received a complete health evaluation, ranging from basic check-ups to advanced medical screenings as required.</p><p style="text-align: justify;">This annual MCU is not merely a routine, but a strategic effort to uphold the company&rsquo;s maritime safety standards and support overall productivity. By maintaining well-monitored health conditions, employees are expected to perform their duties optimally while fostering a safe and sustainable working environment.</p>',
                'featured_image' => 'assets/images/news/1779185004_annual-medical-check-up-2026-a.jpg',
                'youtube_url' => null,
                'author' => 'ABB Media Team',
                'publish_date' => '2026-04-01',
                'meta_title' => 'Annual Medical Check Up 2026 at TZU CHI Hospital',
                'meta_description' => 'Comprehensive health screenings to ensure employee well-being and enforce maritime safety standards.',
                'status' => 'published',
                'view_count' => 71,
                'created_at' => '2026-01-21 08:14:33',
                'updated_at' => '2026-07-20 03:33:52',
            ],
            [
                'id' => 3,
                'category_id' => 5,
                'title' => 'Eco-Green Project: Plastic-Free Vessels',
                'slug' => 'eco-green-project-plastic-free-vessels',
                'excerpt' => 'Implementing sustainable waste management across the entire fleet.',
                'content' => 'No Content',
                'featured_image' => '../assets/images/news/green-vessel.jpg',
                'youtube_url' => null,
                'author' => 'ABB Media Team',
                'publish_date' => '2024-05-05',
                'meta_title' => 'Eco-Green Project: Plastic-Free Vessels',
                'meta_description' => 'Implementing sustainable waste management across the entire fleet.',
                'status' => 'published',
                'view_count' => 55,
                'created_at' => '2026-01-21 08:14:33',
                'updated_at' => '2026-07-20 03:34:08',
            ],
            [
                'id' => 4,
                'category_id' => 3,
                'title' => 'ABB Expands Fleet with Two New Eco-Friendly Vessels',
                'slug' => 'abb-new-eco-vessels',
                'excerpt' => 'Adding modern, fuel-efficient ships to strengthen our operational capacity.',
                'content' => '<p>PT. ABB is proud to announce the acquisition of two new eco-friendly vessels, MV Andalas Green and MV Bahtera Eco. These vessels feature state-of-the-art technology that reduces fuel consumption by 25% and lowers carbon emissions significantly.</p><p>Key features include:</p><ul><li>Advanced hull design for better hydrodynamics</li><li>Energy-efficient engine systems</li><li>Waste heat recovery systems</li><li>Ballast water treatment systems</li></ul><p>This expansion brings our total fleet to 28 vessels, enhancing our capacity to serve clients across Southeast Asia.</p>',
                'featured_image' => '../assets/images/news/new-vessels.jpg',
                'youtube_url' => null,
                'author' => 'ABB Management',
                'publish_date' => '2024-04-20',
                'meta_title' => 'ABB Expands Fleet with Eco-Friendly Vessels',
                'meta_description' => 'PT. ABB adds two new eco-friendly vessels to its fleet, enhancing operational capacity with modern, sustainable technology.',
                'status' => 'published',
                'view_count' => 55,
                'created_at' => '2026-01-22 02:31:05',
                'updated_at' => '2026-07-20 03:34:08',
            ],
            [
                'id' => 5,
                'category_id' => 4,
                'title' => 'End Year Dinner 2025 at HATTORI Japanese Shabu & Yakiniku',
                'slug' => 'end-year-dinner-2025-at-hattori-japanese-shabu-yakiniku',
                'excerpt' => 'An evening of celebration with green & red attire, gift exchange, and exciting door prizes.',
                'content' => '<p>To close the year on a joyful note, PT. Pelayaran Andalas Bahtera Baruna held its End Year Dinner 2025 at HATTORI Japanese Shabu &amp; Yakiniku, Jakarta Utara. The event brought together employees in a festive atmosphere, with the unique concept of wearing green and red attire to symbolize warmth, harmony, and holiday cheer.</p><p>The evening was filled with laughter and camaraderie, highlighted by a gift exchange session that strengthened bonds among colleagues. Excitement peaked during the door prize distribution, where lucky winners brought home special surprises, adding to the spirit of celebration.</p><p>This End Year Dinner not only marked the conclusion of 2025 but also reflected ABB&rsquo;s commitment to fostering togetherness, appreciation, and a positive work culture. With shared joy and memorable moments, the company looks forward to entering the new year with renewed energy and unity.</p>',
                'featured_image' => 'assets/images/news/1778839096_end-year-dinner-2025-at-hattor.jpg',
                'youtube_url' => null,
                'author' => 'ABB Media Team',
                'publish_date' => '2025-12-19',
                'meta_title' => 'End Year Dinner 2025 at HATTORI Japanese Shabu & Yakiniku',
                'meta_description' => 'An evening of celebration with green & red attire, gift exchange, and exciting door prizes.',
                'status' => 'published',
                'view_count' => 58,
                'created_at' => '2026-01-22 02:31:05',
                'updated_at' => '2026-07-20 03:33:59',
            ],
            [
                'id' => 6,
                'category_id' => 5,
                'title' => 'ABB Partners with Local Communities for Coastal Cleanup',
                'slug' => 'abb-coastal-cleanup',
                'excerpt' => 'Joining hands with local communities to protect marine ecosystems.',
                'content' => '<p>PT. ABB, in collaboration with local communities and environmental NGOs, organized a large-scale coastal cleanup program across three locations in Indonesia.</p><p>The initiative achieved:</p><ul><li>Collection of over 2 tons of marine debris</li><li>Planting of 500 mangrove seedlings</li><li>Environmental education for 300 local students</li><li>Installation of waste collection bins in coastal areas</li></ul><p>This program is part of our ongoing commitment to environmental stewardship and community engagement under our CSR framework.</p>',
                'featured_image' => '../assets/images/news/coastal-cleanup.jpg',
                'youtube_url' => null,
                'author' => 'CSR Team',
                'publish_date' => '2024-04-10',
                'meta_title' => 'ABB Coastal Cleanup Initiative Protects Marine Environment',
                'meta_description' => 'PT. ABB partners with local communities for coastal cleanup, removing marine debris and promoting environmental awareness.',
                'status' => 'published',
                'view_count' => 40,
                'created_at' => '2026-01-22 02:31:05',
                'updated_at' => '2026-07-20 03:34:08',
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'title' => 'ABB Achieves ISO 9001:2015 Recertification',
                'slug' => 'abb-iso-recertification-2024',
                'excerpt' => 'Quality management system recertification demonstrates commitment to excellence.',
                'content' => '<p>PT. ABB has successfully achieved recertification for ISO 9001:2015 Quality Management System following a comprehensive audit.</p>',
                'featured_image' => '../assets/images/news/iso-certification.jpg',
                'youtube_url' => null,
                'author' => 'Quality Department',
                'publish_date' => '2024-03-28',
                'meta_title' => 'ABB ISO 9001:2015 Recertification',
                'meta_description' => 'PT. ABB achieves ISO quality management recertification',
                'status' => 'published',
                'view_count' => 44,
                'created_at' => '2026-01-22 04:59:45',
                'updated_at' => '2026-07-20 03:34:08',
            ],
            [
                'id' => 17,
                'category_id' => 4,
                'title' => 'PABB Annual Company Outing 2026 at The Village Resort Bogor',
                'slug' => 'pabb-annual-company-outing-2026-at-the-village-resort-bogor',
                'excerpt' => 'Three days of team building, relaxation, and celebration at the scenic Village Resort Bogor.',
                'content' => '<h2>Strengthening Bonds Through Shared Experiences</h2><p>PT. PABB successfully organized its annual company outing from January 16-18, 2026 at The Village Resort Bogor, bringing together over 100 employees from various departments for three days of team building, relaxation, and celebration.</p><h3>Event Highlights</h3><ul><li><strong>Day 1 - Arrival &amp; Welcome Dinner:</strong> Employees arrived at the resort and were welcomed with a traditional Sundanese dinner accompanied by cultural performances.</li><li><strong>Day 2 - Team Building Activities:</strong> A full day of competitive games including raft building, obstacle courses, and problem-solving challenges designed to enhance teamwork and communication.</li><li><strong>Day 3 - Leadership Sessions &amp; Award Ceremony:</strong> Interactive workshops led by senior management followed by the annual awards ceremony recognizing outstanding employee contributions.</li></ul><h3>Special Activities</h3><p>The resort facilities allowed for various recreational activities:</p><ul><li>Swimming pool games and water sports</li><li>Mountain biking through resort trails</li><li>Traditional cooking classes</li><li>Bonfire night with live music</li></ul><h3>Management Message</h3><blockquote><p>"This annual gathering is more than just a company event - it\"s an investment in our most valuable asset: our people. The bonds formed here translate directly into better collaboration in the workplace."<br>- <strong>Mr. Eldmond Laurenzi, CEO of PT. PABB</strong></p></blockquote><h3>Employee Feedback</h3><p>Participants expressed high satisfaction with the event organization:</p><ul><li>"The team building activities really helped break down departmental barriers." - <em>Sarah, Finance Department</em></li><li>"Great balance between structured activities and free time to relax." - <em>Andi, Operations Team</em></li><li>"The resort setting was perfect for both work and leisure." - <em>Dewi, HR Department</em></li></ul><h3>Looking Ahead</h3><p>Based on the success of this year\'s outing, planning has already begun for the 2027 company gathering, with consideration being given to expanding the event to include employee families.</p><p><strong>Date:</strong> January 16-18, 2026<br><strong>Location:</strong> The Village Resort, Bogor<br><strong>Participants:</strong> 120 employees across all departments<br><strong>Theme:</strong> "One Team, One Vision"</p>',
                'featured_image' => 'assets/images/news/1773119467_abb-annual-company-outing-2026.jpg',
                'youtube_url' => null,
                'author' => 'ABB Media Team',
                'publish_date' => '2026-01-16',
                'meta_title' => 'PABB Annual Company Outing 2026 at The Village Resort Bogor',
                'meta_description' => 'Three days of team building, relaxation, and celebration at the scenic Village Resort Bogor.',
                'status' => 'published',
                'view_count' => 92,
                'created_at' => '2026-01-22 07:22:37',
                'updated_at' => '2026-07-20 03:33:57',
            ],
            [
                'id' => 18,
                'category_id' => 4,
                'title' => 'ABB Celebrates Chinese New Year, Ramadan Gathering & 26th Anniversary',
                'slug' => 'abb-celebrates-chinese-new-year-ramadan-gathering-26th-anniversary',
                'excerpt' => 'Halal Bihalal Imlek 2577 Kongzili & Ramadan Gathering Celebrating ABB’s 26th Anniversary – 2026',
                'content' => '<h2><strong>Halal Bihalal Imlek 2577 Kongzili &amp; Ramadan Gathering Celebrating ABB&rsquo;s 26th Anniversary &ndash; 2026</strong></h2><figure class="image image-style-align-left"><img style="aspect-ratio: 800/600;" src="../assets/images/news/inline_1773197621_820.jpg" width="800" height="600"></figure><p><br>PT. Pelayaran Andalas Bahtera Baruna (ABB) held a special evening of celebration and fellowship to commemorate the Chinese New Year of 2577 Kongzili, a Ramadan gathering, and the company&rsquo;s 26th anniversary.</p><p>The event took place on Tuesday, March 3, 2026, at Hotel Mercure Jakarta Batavia, bringing together management, employees, and invited partners in a warm atmosphere of appreciation and togetherness.</p><p>This meaningful gathering served as a moment to strengthen relationships among ABB&rsquo;s team members and to reflect on the company&rsquo;s journey over the past 26 years. Through shared traditions and cultural harmony, the event highlighted ABB&rsquo;s commitment to unity, mutual respect, and a collaborative working environment.</p><p>During the evening, guests enjoyed a series of activities including remarks from company leadership, celebratory moments marking ABB&rsquo;s anniversary milestone, and a communal iftar during the holy month of Ramadan.</p><p>The celebration also reflected ABB&rsquo;s appreciation for cultural diversity, embracing both the spirit of Chinese New Year and the values of togetherness during Ramadan.</p><p>As ABB continues to grow and expand its maritime operations, events such as this reinforce the company&rsquo;s strong organizational culture &mdash; one built on teamwork, respect, and shared success.</p><p>The evening concluded with renewed optimism for the future as ABB moves forward with continued dedication to operational excellence and strong partnerships across the maritime industry.</p>',
                'featured_image' => 'assets/images/news/1773129852_abb-celebrates-chinese-new-yea.jpg',
                'youtube_url' => null,
                'author' => 'ABB Media Team',
                'publish_date' => '2026-03-03',
                'meta_title' => 'ABB Celebrates Chinese New Year, Ramadan Gathering & 26th Anniversary',
                'meta_description' => 'Halal Bihalal Imlek 2577 Kongzili & Ramadan Gathering Celebrating ABB’s 26th Anniversary – 2026',
                'status' => 'published',
                'view_count' => 104,
                'created_at' => '2026-01-22 09:09:38',
                'updated_at' => '2026-07-20 03:33:55',
            ]
        ]);

        // 7. Seed careers
        DB::table('careers')->insert([
            [
                'id' => 1, 'author_id' => null,
                'position' => 'General Manager Operations', 'department' => 'Operations', 'category' => 'corporate', 'location' => 'Jakarta HQ',
                'employment_type' => 'fulltime', 'description' => 'Leading the strategic maritime operations and fleet efficiency.',
                'requirements' => 'Minimum 10 years experience in senior maritime management.', 'responsibilities' => '', 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-03-08 07:51:23',
            ],
            [
                'id' => 2, 'author_id' => null,
                'position' => 'Senior Finance Controller', 'department' => 'Finance', 'category' => 'corporate', 'location' => 'Jakarta HQ',
                'employment_type' => 'fulltime', 'description' => 'Managing corporate financial planning and tax strategy.',
                'requirements' => 'CA/CPA qualification with 7+ years in maritime finance.', 'responsibilities' => "• Financial reporting\n• Budget management\n• Tax planning\n• Audit coordination", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-01-21 08:14:33',
            ],
            [
                'id' => 4, 'author_id' => null,
                'position' => 'Senior Technical Buyer', 'department' => 'Procurement', 'category' => 'corporate', 'location' => 'Jakarta HQ',
                'employment_type' => 'fulltime', 'description' => 'Managing global supply chain for engine parts and dry-docking.',
                'requirements' => 'Technical degree with 5 years experience in marine procurement.', 'responsibilities' => "• Vendor management\n• Procurement planning\n• Quality control\n• Inventory management", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-01-21 08:14:33',
            ],
            [
                'id' => 5, 'author_id' => null,
                'position' => 'Corporate Legal Counsel', 'department' => 'Legal', 'category' => 'corporate', 'location' => 'Jakarta HQ',
                'employment_type' => 'fulltime', 'description' => 'Handling maritime contracts, charter parties, and compliance.',
                'requirements' => 'Master of Law (LLM) with focus on International Maritime Law.', 'responsibilities' => "• Contract drafting\n• Legal compliance\n• Dispute resolution\n• Regulatory advisory", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-01-21 08:14:33',
            ],
            [
                'id' => 6, 'author_id' => null,
                'position' => 'Vessel Master (Captain)', 'department' => 'Deck', 'category' => 'crew', 'location' => 'Regional Fleet',
                'employment_type' => 'fulltime', 'description' => 'Overall command of tanker vessels ensuring safety and compliance.',
                'requirements' => 'Master Mariner Class I (ANT I) with tanker endorsements.', 'responsibilities' => "• Vessel navigation\n• Crew management\n• Safety procedures\n• Port operations", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-03-08 07:50:25',
            ],
            [
                'id' => 7, 'author_id' => null,
                'position' => 'Chief Engineer', 'department' => 'Engine', 'category' => 'crew', 'location' => 'Regional Fleet',
                'employment_type' => 'fulltime', 'description' => 'Responsible for main engine maintenance and technical operations.',
                'requirements' => 'Marine Engineer Class I (ATT I) with experience in low-speed engines.', 'responsibilities' => "• Engine maintenance\n• Technical troubleshooting\n• Spare parts management\n• Safety inspections", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-02-21 06:03:42',
            ],
            [
                'id' => 8, 'author_id' => null,
                'position' => 'Second Officer', 'department' => 'Deck', 'category' => 'crew', 'location' => 'Regional Fleet',
                'employment_type' => 'fulltime', 'description' => 'Assisting in navigation watches and safety equipment maintenance.',
                'requirements' => 'ANT II/III certificate with valid STCW documents.', 'responsibilities' => "• Navigation watch\n• Safety equipment checks\n• Chart updates\n• Port documentation", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-02-21 06:03:42',
            ],
            [
                'id' => 9, 'author_id' => null,
                'position' => 'Pumpman / Deck Fitter', 'department' => 'Engine/Cargo', 'category' => 'crew', 'location' => 'Regional Fleet',
                'employment_type' => 'fulltime', 'description' => 'Specialized maintenance of cargo pumping systems on tankers.',
                'requirements' => 'Certified Pumpman with specialized tanker training.', 'responsibilities' => "• Pump system maintenance\n• Cargo operations\n• Deck maintenance\n• Safety procedures", 'status' => 'open',
                'application_deadline' => '2026-03-31', 'created_at' => '2026-01-21 08:14:33', 'updated_at' => '2026-02-21 06:03:42',
            ]
        ]);

        // 8. Seed clients
        DB::table('clients')->insert([
            ['id' => 40, 'name' => 'PT. Bahtera Bestari Shipping', 'category' => 'domestic', 'logo' => '1777650268_PT__Bahtera_Bes.png', 'created_at' => '2026-04-06 15:34:51', 'updated_at' => '2026-05-01 15:44:28'],
            ['id' => 41, 'name' => 'PT. Bahtera Alam Sejahtera', 'category' => 'domestic', 'logo' => '1777650146_PT__Bahtera_Ala.png', 'created_at' => '2026-04-06 15:35:25', 'updated_at' => '2026-05-01 15:42:26'],
            ['id' => 42, 'name' => 'PT. Dian Bahari Sejati', 'category' => 'domestic', 'logo' => '1777650114_PT__Dian_Bahari.png', 'created_at' => '2026-04-06 15:36:13', 'updated_at' => '2026-05-01 15:41:54'],
            ['id' => 43, 'name' => 'PT. Lafarge Cement Indonesia, Tbk', 'category' => 'domestic', 'logo' => '1777650087_PT__Lafarge_Cem.png', 'created_at' => '2026-04-06 15:37:41', 'updated_at' => '2026-05-01 15:41:27'],
            ['id' => 44, 'name' => 'PT. Solusi Bangun Indonesia, Tbk', 'category' => 'domestic', 'logo' => '1777649875_PT__Solusi_Bang.png', 'created_at' => '2026-04-06 15:38:07', 'updated_at' => '2026-05-01 15:37:55'],
            ['id' => 45, 'name' => 'PT. Semen Padang', 'category' => 'domestic', 'logo' => '1777649829_PT__Semen_Padan.png', 'created_at' => '2026-04-06 15:38:40', 'updated_at' => '2026-05-01 15:37:09'],
            ['id' => 46, 'name' => 'PT. Semen Bosowa Maros', 'category' => 'domestic', 'logo' => '1777649795_PT__Semen_Bosow.png', 'created_at' => '2026-04-06 15:39:00', 'updated_at' => '2026-05-01 15:36:35'],
            ['id' => 47, 'name' => 'PT. Semen Tonasa', 'category' => 'domestic', 'logo' => '1777649742_PT__Semen_Tonas.png', 'created_at' => '2026-04-06 15:39:23', 'updated_at' => '2026-05-01 15:35:42'],
            ['id' => 48, 'name' => 'PT. Semen Bosowa Indonesia', 'category' => 'domestic', 'logo' => '1777649674_PT__Semen_Bosow.png', 'created_at' => '2026-04-06 15:39:43', 'updated_at' => '2026-05-01 15:34:34'],
            ['id' => 49, 'name' => 'PT. Cemindo Gemilang', 'category' => 'domestic', 'logo' => '1777649646_PT__Cemindo_Gem.png', 'created_at' => '2026-04-06 15:40:02', 'updated_at' => '2026-05-01 15:34:06'],
            ['id' => 50, 'name' => 'PT. Indocement Tunggal Perkasa, Tbk', 'category' => 'domestic', 'logo' => '1777649352_PT__Indocement_.png', 'created_at' => '2026-04-06 15:40:20', 'updated_at' => '2026-05-01 15:29:12'],
            ['id' => 51, 'name' => 'PT. Semen Gresik', 'category' => 'domestic', 'logo' => '1777649295_PT__Semen_Gresi.png', 'created_at' => '2026-04-06 15:40:45', 'updated_at' => '2026-05-01 15:28:15'],
            ['id' => 52, 'name' => 'PT. Semen Indonesia (Persero), Tbk', 'category' => 'domestic', 'logo' => '1777649240_PT__Semen_Indon.png', 'created_at' => '2026-04-06 15:41:05', 'updated_at' => '2026-05-01 15:27:20'],
            ['id' => 53, 'name' => 'Minti International', 'category' => 'international', 'logo' => '1777649193_Minti_Internati.png', 'created_at' => '2026-04-06 15:42:03', 'updated_at' => '2026-05-01 15:26:33'],
            ['id' => 54, 'name' => 'Max Bridge', 'category' => 'international', 'logo' => '1777649156_Max_Bridge.png', 'created_at' => '2026-04-06 15:42:20', 'updated_at' => '2026-05-01 15:25:56'],
            ['id' => 55, 'name' => 'KRnG Indonesia', 'category' => 'international', 'logo' => '1777648379_KRnG_Indonesia.png', 'created_at' => '2026-04-06 15:42:38', 'updated_at' => '2026-05-01 15:12:59'],
            ['id' => 56, 'name' => 'KGJS Cement', 'category' => 'international', 'logo' => '1777648348_KGJS_Cement.png', 'created_at' => '2026-04-06 15:43:09', 'updated_at' => '2026-05-01 15:12:28'],
            ['id' => 57, 'name' => 'United Ocean Shipping (UOS) Co., Ltd', 'category' => 'international', 'logo' => '1777648264_United_Ocean_Sh.png', 'created_at' => '2026-04-06 15:43:47', 'updated_at' => '2026-05-01 15:11:04'],
            ['id' => 58, 'name' => 'Shinchang Shipping Co., Ltd', 'category' => 'international', 'logo' => '1777648213_Shinchang_Shipp.png', 'created_at' => '2026-04-06 15:44:04', 'updated_at' => '2026-05-01 15:10:13'],
            ['id' => 59, 'name' => 'Ranchan Maritime Sdn Bhd', 'category' => 'international', 'logo' => '1777648179_Ranchan_Maritim.png', 'created_at' => '2026-04-06 15:44:44', 'updated_at' => '2026-05-01 15:09:39'],
            ['id' => 60, 'name' => 'Weltrans Marine Services Inc.', 'category' => 'international', 'logo' => '1777648070_Weltrans_Marine.png', 'created_at' => '2026-04-06 15:45:12', 'updated_at' => '2026-05-01 15:07:50'],
            ['id' => 61, 'name' => 'Full Max Corporation Limited', 'category' => 'international', 'logo' => '1777648024_Full_Max_Corpor.png', 'created_at' => '2026-04-06 15:45:28', 'updated_at' => '2026-05-01 15:07:04'],
            ['id' => 62, 'name' => 'Jumewah Shipping Sdn Bhd (YTL Group)', 'category' => 'international', 'logo' => '1777647999_Jumewah_Shippin.png', 'created_at' => '2026-04-06 15:45:54', 'updated_at' => '2026-05-01 15:06:39'],
            ['id' => 63, 'name' => 'Asia Cement Corporation', 'category' => 'international', 'logo' => 'acc.png', 'created_at' => '2026-04-06 15:46:07', 'updated_at' => '2026-05-01 15:06:08'],
            ['id' => 64, 'name' => 'Taiwan Cement', 'category' => 'international', 'logo' => 'tcc.png', 'created_at' => '2026-04-06 15:46:32', 'updated_at' => '2026-05-01 15:04:42'],
            ['id' => 65, 'name' => 'Sampyo Cement', 'category' => 'international', 'logo' => 'sampyo.png', 'created_at' => '2026-04-06 15:46:49', 'updated_at' => '2026-05-01 14:58:57'],
            ['id' => 66, 'name' => 'Sangyoung Cement', 'category' => 'international', 'logo' => 'sangyoung.png', 'created_at' => '2026-04-06 15:47:08', 'updated_at' => '2026-05-01 14:57:48'],
            ['id' => 67, 'name' => 'Republic Cement Iligan, Inc', 'category' => 'international', 'logo' => 'iligan.png', 'created_at' => '2026-04-06 15:47:23', 'updated_at' => '2026-05-01 14:57:13'],
            ['id' => 68, 'name' => 'Lafarge Holcim Malaysia', 'category' => 'international', 'logo' => 'lafarge.png', 'created_at' => '2026-04-06 15:47:40', 'updated_at' => '2026-05-01 14:56:14'],
            ['id' => 70, 'name' => 'Raysut Cement Company', 'category' => 'international', 'logo' => '1777642947_Raysut_Cement_C.png', 'created_at' => '2026-05-01 13:42:27', 'updated_at' => '2026-05-01 13:42:27'],
            ['id' => 71, 'name' => 'Cementis Group', 'category' => 'international', 'logo' => '1778835519_Cementis_Group.png', 'created_at' => '2026-05-15 08:58:39', 'updated_at' => '2026-05-15 08:58:39'],
        ]);

        // 9. Seed contact_info
        DB::table('contact_info')->insert([
            ['id' => 1, 'type' => 'office', 'label' => 'Kantor Pusat', 'value' => 'Jl. Pelabuhan No. 123, Jakarta', 'icon' => 'location', 'is_primary' => true, 'display_order' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'type' => 'phone', 'label' => 'Telepon', 'value' => '+62-21-1234567', 'icon' => 'phone', 'is_primary' => true, 'display_order' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'type' => 'email', 'label' => 'Email Commercial', 'value' => 'commercial@abb.com', 'icon' => 'email', 'is_primary' => true, 'display_order' => 3, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // 10. Seed notifications
        DB::table('notifications')->insert([
            ['id' => 1, 'title' => 'BEWARE OF RECRUITMENT SCAMS!', 'type' => 'career', 'content' => 'PT. Pelayaran Andalas Bahtera Baruna (PT. ABB) NEVER requests any fees, payments, or uses third-party travel agents during the recruitment process. All official communications will only come from emails ending in @ptabb.com.', 'image' => null, 'status' => 'active', 'created_at' => '2026-02-23 03:59:10', 'updated_at' => '2026-02-23 03:59:10'],
        ]);

        // 11. Seed settings
        DB::table('settings')->insert([
            ['id' => 1, 'setting_key' => 'company_name', 'setting_value' => 'PT. Pelayaran Andalas Bahtera Baruna', 'setting_type' => 'text', 'description' => 'Nama perusahaan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'setting_key' => 'company_abbreviation', 'setting_value' => 'ABB', 'setting_type' => 'text', 'description' => 'Singkatan nama perusahaan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'setting_key' => 'company_full_name', 'setting_value' => 'PT. Pelayaran Andalas Bahtera Baruna', 'setting_type' => 'text', 'description' => 'Nama lengkap perusahaan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'setting_key' => 'company_tagline', 'setting_value' => 'Connecting Markets with Maritime Excellence', 'setting_type' => 'text', 'description' => 'Tagline perusahaan', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'setting_key' => 'primary_color', 'setting_value' => '#1b5983', 'setting_type' => 'text', 'description' => 'Warna utama website', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'setting_key' => 'secondary_color', 'setting_value' => '#743c3a', 'setting_type' => 'text', 'description' => 'Warna sekunder website', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'setting_key' => 'logo_url', 'setting_value' => 'assets/images/logo-abb.jpg', 'setting_type' => 'text', 'description' => 'URL logo perusahaan', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // 12. Seed Indonesian Celebration Days popups
        $this->call(IndonesianCelebrationDaysSeeder::class);
    }
}
